spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/FIS

server:
  port: 8080

jwt:
  auth:
    converter:
      resource-id: FIS_backend
      principal-attribute: preferred_username